CREATE DATABASE VIDEOGAME;
USE VIDEOGAME;

CREATE TABLE ORIGEN_VIRUS(
	ID      		INT AUTO_INCREMENT PRIMARY KEY,
	ORIGEN  		VARCHAR(70) NOT NULL,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME
)ENGINE=INNODB;

CREATE TABLE ZOMBIES(
	ID              INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE          VARCHAR(70) NOT NULL,
	DESCRIPCION     TEXT NULL,
	ORIGEN_VIRUS_ID INT NOT NULL,
	VELOCIDAD       TINYINT UNSIGNED NOT NULL,
	FUERZA          TINYINT UNSIGNED NOT NULL,
	RESISTENCIA     TINYINT UNSIGNED NOT NULL,
	HUMANIDAD       TINYINT UNSIGNED NOT NULL,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME,
	FOREIGN KEY (ORIGEN_VIRUS_ID) REFERENCES ORIGEN_VIRUS(ID)
)ENGINE=INNODB;